# Generated by Django 4.1.6 on 2023-02-06 14:36

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=catalog.models.get_default_field_id, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
