# Generated by Django 4.1.6 on 2023-02-08 16:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateTimeField(blank=True, default=blog.models.actual_date, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='create_date',
            field=models.DateTimeField(blank=True, default=blog.models.actual_date, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(blank=True, default=blog.models.actual_date, null=True),
        ),
    ]
