# Generated by Django 4.1.6 on 2023-02-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['create_date'], 'permissions': (('can_add_blog', 'Blogs moder'),)},
        ),
    ]
