# Generated by Django 4.1.6 on 2023-02-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenimport',
            name='token_bizon',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viewersimport',
            name='banners',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='viewersimport',
            name='buttons',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='viewersimport',
            name='webroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.webroomtransaction'),
        ),
    ]
