# Generated by Django 4.1.6 on 2023-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_alter_webroomtransaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenimport',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
